layers:
  - name: contextual
    enabled: true
  - name: semantic
    enabled: true
  - name: visual
    enabled: false
  - name: impact
    enabled: true
  - name: consistency
    enabled: true
  - name: meta
    enabled: true

limits:
  max_context_size: 50000
  max_chain_tokens: 6000

caching:
  lru_size: 256